inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

inherit_mode:
  merge:
    - Exclude

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Lint/UnreachableLoop:
  Exclude:
    - spec/lib/health_answers_list_spec.rb

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always_true

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - staging
    - production
