inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - scratchpad/*

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Rails/UnknownEnv:
  Environments:
    - development
    - production
    - staging
    - test

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always_true
