inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

inherit_mode:
  merge:
    - Exclude

Lint/UnreachableLoop:
  Exclude:
    - spec/lib/health_answers_list_spec.rb

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - staging
    - production

Style/BlockDelimiters:
  Exclude:
    - lib/example_campaign_generator.rb

Style/MethodCalledOnDoEndBlock:
  Exclude:
    - lib/example_campaign_generator.rb
