name: Lint

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn prettier --check --ignore-unknown '**/*'

  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: bin/bundle exec rubocop

  rufo:
    name: Rufo
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bin/bundle exec rufo --check app

  brakeman:
    name: Brakeman
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bin/bundle exec brakeman
